baseURL                = "https://www.joseph-edwards.github.io"
defaultContentLanguage = "en"
enableEmoji            = true
languageCode           = "en"
theme                  = "coder"
title                  = "Joseph Edwards"

[pagination]
pagerSize = 6


[markup]
[markup.highlight]
noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[params]
author      = "Joseph Edwards"
avatarURL   = "images/avatar.jpg"
dateFormat  = "2 January 2006"
description = "Joseph Edwards's academic profile"
info        = ["Mathematics PhD Student", "University of St Andrews"]
keywords    = "mathematician,developer,semigroups"
since       = 2025
# Git Commit in Footer, uncomment the line below to enable it
# commit = "https://github.com/luizdepra/hugo-coder/tree/"
colorScheme = "auto"
customCSS = []
customJS = []
customRemoteJS = []
customSCSS = [
    "scss/project.scss",
    "scss/project_dark.scss",
    "scss/talk.scss",
    "scss/talk_dark.scss",
]
hideColorSchemeToggle = false
maxSeeAlsoItems = 5

# [taxonomies]
# author   = "authors"
# category = "categories"
# series   = "series"
# tag      = "tags"

[[params.social]]
icon   = "fa-brands fa-github fa-2x"
name   = "Github"
url    = "https://github.com/joseph-edwards/"
weight = 1

[[params.social]]
icon   = "fa-brands fa-linkedin fa-2x"
name   = "LinkedIn"
url    = "https://www.linkedin.com/in/joseph-edwards-01/"
weight = 2

[[params.social]]
icon   = "fa-brands fa-orcid fa-2x"
name   = "Orcid"
url    = "https://orcid.org/0009-0005-3803-2758"
weight = 3

[[params.social]]
icon   = "fa-solid fa-envelope fa-2x"
name   = "Email"
url    = "mailto:jde1@st-andrews.ac.uk"
weight = 4


[[menu.main]]
name   = "About"
url    = "about/"
weight = 1

[[menu.main]]
name   = "Publications"
url    = "publications/"
weight = 2

[[menu.main]]
name   = "Software"
url    = "software/"
weight = 3

[[menu.main]]
name   = "Talks"
url    = "talks/"
weight = 4

[[menu.main]]
name   = "Teaching"
url    = "teaching/"
weight = 5

[caches.images]
dir = ':cacheDir/images'
